### ISSUE TITLE
Getting rid of LaTeX 

### ISSUE THREAD

**Issue by paulhenke** [fsr/csharp-lessons#4]
LaTeX is ~~fugly~~ terrible, any chance of using something readable i.e. AsciiDoc?

It's plaintext-readable and Github understands it.

**Comment by Feliix42** [comment]
I don't think that we will be switching over to Asciidoc in the near future.
Behind these repositories sits an infrastructure to automatically build and deploy the slides to our web server via webhook and since all our course material repositories are based on the same foundation it would require a great amount of work to rewrite the materials for five complete courses.

Additionally, we are using packages like `tikz` and `listings` to fill our presentations with graphics and highlighted source code snippets. At least the former is nothing Asciidoc supports out of the box (not to mention PDF document export in presentation format). 😉 

If you are looking for a rendered version of the slides in **master**, you can have a look [here](https://fsr.github.io/csharp-lessons/materials.html). 
But if you are specifically asking or a rewrite: Sorry, there won't be one in the near future.
